name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backcall=0.2.0
  - bleach=3.1.5
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.2
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.34
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.3
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.6
  - prompt_toolkit=3.0.6
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - bert-extractive-summarizer==0.5.0
    - blis==0.4.1
    - cachetools==4.1.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.2
    - cymem==2.0.3
    - dill==0.3.2
    - en-core-web-md==2.3.1
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - idna==2.10
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - murmurhash==1.0.2
    - nlp==0.4.0
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.1.1
    - pillow==7.2.0
    - plac==1.1.3
    - preshed==3.0.2
    - protobuf==3.13.0
    - pyarrow==1.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-slugify==4.0.1
    - pytz==2020.1
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - sentencepiece==0.1.91
    - spacy==2.3.2
    - srsly==1.0.2
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - tokenizers==0.8.1rc1
    - torch==1.6.0
    - torchvision==0.7.0
    - tqdm==4.48.2
    - transformers==3.0.2
    - urllib3==1.24.3
    - wasabi==0.8.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xxhash==2.0.0
